# Generated by Django 2.2.5 on 2019-10-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='title',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='chat',
            name='topic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
