# Generated by Django 2.2.5 on 2019-11-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20191030_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user'},
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='qwerty', max_length=100),
        ),
    ]
