# Generated by Django 2.2.5 on 2019-11-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20191106_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': ('Пользователь',), 'verbose_name_plural': 'Пользователи'},
        ),
    ]
