# Generated by Django 2.2.5 on 2019-11-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20191113_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nick',
        ),
    ]
