# Generated by Django 2.2.5 on 2019-10-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('chats', '0002_auto_20191028_2209'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50)),
                ('url', models.URLField(null=True)),
                ('chat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_chat_id', to='chats.Chat')),
                ('message_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_message_id', to='message.Message')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_user_id', to='user_profile.User')),
            ],
        ),
    ]
