# Generated by Django 2.2.5 on 2019-11-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0003_auto_20191106_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': ('Прикрепление',), 'verbose_name_plural': 'Прикрепления'},
        ),
    ]
