# Generated by Django 2.2.5 on 2019-11-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0002_auto_20191030_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'channel_member'},
        ),
    ]
