# Generated by Django 2.2.5 on 2019-11-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0003_auto_20191106_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': ('Участник чата',), 'verbose_name_plural': 'Участники чата'},
        ),
    ]
