# Generated by Django 2.2.5 on 2019-11-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20191030_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'message'},
        ),
    ]
