# Generated by Django 2.2.5 on 2019-11-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20191106_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': ('Сообщение',), 'verbose_name_plural': 'Сообщения'},
        ),
    ]
