# Generated by Django 2.2.5 on 2019-11-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20191112_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-added_at',), 'verbose_name': ('Сообщение',), 'verbose_name_plural': 'Сообщения'},
        ),
    ]
